export const CALENDAR_DAY = {
  MONDAY: 'monday',
  TUESDAY: 'tuesday',
  WEDNESDAY: 'wednesday',
  THURSDAY: 'thursday',
  FRIDAY: 'friday',
  SATURDAY: 'saturday',
  SUNDAY: 'sunday',
};

export const CALENDAR_DAY_ORDER = [
  CALENDAR_DAY.MONDAY,
  CALENDAR_DAY.TUESDAY,
  CALENDAR_DAY.WEDNESDAY,
  CALENDAR_DAY.THURSDAY,
  CALENDAR_DAY.FRIDAY,
  CALENDAR_DAY.SATURDAY,
  CALENDAR_DAY.SUNDAY,
];

export const CALENDAR_INTERVAL = {
  XXSMALL: 1,
  XSMALL: 5,
  SMALL: 15,
  MEDIUM: 30,
  LARGE: 60,
  XLARGE: 120,
  XXLARGE: 240,
};

export const CALENDAR_PRECISION = {
  FINE: 1,
  NORMAL: 5,
  COURSE: 15,
  HOURLY: 60,
};
